In [3]:
import pandas as pd

print("Pandas is working!")
print(f"Pandas version: {pd.__version__}")

Pandas is working!
Pandas version: 3.0.1

In [4]:
import pandas as pd

df = pd.read_csv("sample.csv")

df.head()

  product category  price  quantity
0   Apple  Produce   1.99       150
1    Milk    Dairy   3.49        80
2   Bread   Bakery   2.99        60
3  Cheese    Dairy   5.99        45
4    Eggs    Dairy   4.49        90

In [5]:
dairy = df[df["category"] == "Dairy"]
dairy

  product category  price  quantity
1    Milk    Dairy   3.49        80
3  Cheese    Dairy   5.99        45
4    Eggs    Dairy   4.49        90

In [6]:
df["total_value"] = df["price"] * df["quantity"]
df

  product category  price  quantity  total_value
0   Apple  Produce   1.99       150       298.50
1    Milk    Dairy   3.49        80       279.20
2   Bread   Bakery   2.99        60       179.40
3  Cheese    Dairy   5.99        45       269.55
4    Eggs    Dairy   4.49        90       404.10

In [7]:
df.groupby("category")["total_value"].sum()

category
Bakery     179.40
Dairy      952.85
Produce    298.50
Name: total_value, dtype: float64

In [8]:
df.to_excel("product_summary.xlsx", index=False)

print("File saved!")

File saved!

In [9]:
name = "Rick"
age = 30
price = 4.99
is_active = True

print(name)
print(age)
print(price)
print(is_active)

Rick
30
4.99
True

In [10]:
# Combining variables - like building a formula in Excel
product = "Milk"
price = 3.49
quantity = 80

total = price * quantity

print(f"{product} total value: ${total}")

Milk total value: $279.20000000000005

In [11]:
# Lists
products = ["Apple", "Milk", "Bread", "Cheese", "Eggs"]
prices = [1.99, 3.49, 2.99, 5.99, 4.49]

print(products)
print(prices)

# Access a single item - just like referencing a cell in Excel
print(products[0])  # First item
print(products[2])  # Third item

['Apple', 'Milk', 'Bread', 'Cheese', 'Eggs']
[1.99, 3.49, 2.99, 5.99, 4.49]
Apple
Bread

In [12]:
for product in products:
    print(f"Product: {product}")

Product: Apple
Product: Milk
Product: Bread
Product: Cheese
Product: Eggs

In [13]:
for i in range(len(products)):
    if prices[i] > 3.00:
        print(f"{products[i]} is expensive: ${prices[i]}")
    else:
        print(f"{products[i]} is affordable: ${prices[i]}")

Apple is affordable: $1.99
Milk is expensive: $3.49
Bread is affordable: $2.99
Cheese is expensive: $5.99
Eggs is expensive: $4.49

In [14]:
# Define a function
def calculate_total(price, quantity):
    total = price * quantity
    return total

# Use the function
print(calculate_total(3.49, 80))
print(calculate_total(5.99, 45))
print(calculate_total(1.99, 150))

279.20000000000005
269.55
298.5

In [15]:
quantities = [150, 80, 60, 45, 90]

def calculate_total(price, quantity):
    return round(price * quantity, 2)
for i in range(len(products)):
    total = calculate_total(prices[i], quantities[i])
    print(f"{products[i]}: ${total}")

Apple: $298.5
Milk: $279.2
Bread: $179.4
Cheese: $269.55
Eggs: $404.1

In [16]:
# A dictionary
product = {
    "name": "Milk",
    "category": "Dairy",
    "price": 3.49,
    "quantity": 80
}

print(product["name"])
print(product["price"])
print(product["quantity"])

Milk
3.49
80

In [18]:
# List of dictionaries - like a table
products_data = [
    {"name": "Apple",  "category": "Produce", "price": 1.99, "quantity": 150},
    {"name": "Milk",   "category": "Dairy",   "price": 3.49, "quantity": 80},
    {"name": "Bread",  "category": "Bakery",  "price": 2.99, "quantity": 60},
    {"name": "Cheese", "category": "Dairy",   "price": 5.99, "quantity": 45},
    {"name": "Eggs",   "category": "Dairy",   "price": 4.49, "quantity": 90}
]

# Loop through each row
for product in products_data:
    total = calculate_total(product["price"], product["quantity"])
    print(f"{product['name']} ({product['category']}): ${total}")

Apple (Produce): $298.5
Milk (Dairy): $279.2
Bread (Bakery): $179.4
Cheese (Dairy): $269.55
Eggs (Dairy): $404.1

In [19]:
import pandas as pd

df2 = pd.DataFrame(products_data)
df2

     name category  price  quantity
0   Apple  Produce   1.99       150
1    Milk    Dairy   3.49        80
2   Bread   Bakery   2.99        60
3  Cheese    Dairy   5.99        45
4    Eggs    Dairy   4.49        90