In [68]:
import pandas as pd

print("Pandas is working!")
print(f"Pandas version: {pd.__version__}")

Pandas is working!
Pandas version: 3.0.1

In [69]:
import pandas as pd

df = pd.read_csv("sample.csv")

df.head()

  product category  price  quantity
0   Apple  Produce   1.99       150
1    Milk    Dairy   3.49        80
2   Bread   Bakery   2.99        60
3  Cheese    Dairy   5.99        45
4    Eggs    Dairy   4.49        90

In [70]:
dairy = df[df["category"] == "Dairy"]
dairy

  product category  price  quantity
1    Milk    Dairy   3.49        80
3  Cheese    Dairy   5.99        45
4    Eggs    Dairy   4.49        90

In [71]:
df["total_value"] = df["price"] * df["quantity"]
df

  product category  price  quantity  total_value
0   Apple  Produce   1.99       150       298.50
1    Milk    Dairy   3.49        80       279.20
2   Bread   Bakery   2.99        60       179.40
3  Cheese    Dairy   5.99        45       269.55
4    Eggs    Dairy   4.49        90       404.10

In [72]:
df.groupby("category")["total_value"].sum()

category
Bakery     179.40
Dairy      952.85
Produce    298.50
Name: total_value, dtype: float64

In [73]:
df.to_excel("product_summary.xlsx", index=False)

print("File saved!")

File saved!

In [74]:
name = "Rick"
age = 30
price = 4.99
is_active = True

print(name)
print(age)
print(price)
print(is_active)

Rick
30
4.99
True

In [75]:
# Combining variables - like building a formula in Excel
product = "Milk"
price = 3.49
quantity = 80

total = price * quantity

print(f"{product} total value: ${total}")

Milk total value: $279.20000000000005

In [76]:
# Lists
products = ["Apple", "Milk", "Bread", "Cheese", "Eggs"]
prices = [1.99, 3.49, 2.99, 5.99, 4.49]

print(products)
print(prices)

# Access a single item - just like referencing a cell in Excel
print(products[0])  # First item
print(products[2])  # Third item

['Apple', 'Milk', 'Bread', 'Cheese', 'Eggs']
[1.99, 3.49, 2.99, 5.99, 4.49]
Apple
Bread

In [77]:
for product in products:
    print(f"Product: {product}")

Product: Apple
Product: Milk
Product: Bread
Product: Cheese
Product: Eggs

In [78]:
for i in range(len(products)):
    if prices[i] > 3.00:
        print(f"{products[i]} is expensive: ${prices[i]}")
    else:
        print(f"{products[i]} is affordable: ${prices[i]}")

Apple is affordable: $1.99
Milk is expensive: $3.49
Bread is affordable: $2.99
Cheese is expensive: $5.99
Eggs is expensive: $4.49

In [79]:
# Define a function
def calculate_total(price, quantity):
    total = price * quantity
    return total

# Use the function
print(calculate_total(3.49, 80))
print(calculate_total(5.99, 45))
print(calculate_total(1.99, 150))

279.20000000000005
269.55
298.5

In [80]:
quantities = [150, 80, 60, 45, 90]

def calculate_total(price, quantity):
    return round(price * quantity, 2)
for i in range(len(products)):
    total = calculate_total(prices[i], quantities[i])
    print(f"{products[i]}: ${total}")

Apple: $298.5
Milk: $279.2
Bread: $179.4
Cheese: $269.55
Eggs: $404.1

In [81]:
# A dictionary
product = {
    "name": "Milk",
    "category": "Dairy",
    "price": 3.49,
    "quantity": 80
}

print(product["name"])
print(product["price"])
print(product["quantity"])

Milk
3.49
80

In [82]:
# List of dictionaries - like a table
products_data = [
    {"name": "Apple",  "category": "Produce", "price": 1.99, "quantity": 150},
    {"name": "Milk",   "category": "Dairy",   "price": 3.49, "quantity": 80},
    {"name": "Bread",  "category": "Bakery",  "price": 2.99, "quantity": 60},
    {"name": "Cheese", "category": "Dairy",   "price": 5.99, "quantity": 45},
    {"name": "Eggs",   "category": "Dairy",   "price": 4.49, "quantity": 90}
]

# Loop through each row
for product in products_data:
    total = calculate_total(product["price"], product["quantity"])
    print(f"{product['name']} ({product['category']}): ${total}")

Apple (Produce): $298.5
Milk (Dairy): $279.2
Bread (Bakery): $179.4
Cheese (Dairy): $269.55
Eggs (Dairy): $404.1

In [83]:
import pandas as pd

df2 = pd.DataFrame(products_data)
df2

     name category  price  quantity
0   Apple  Produce   1.99       150
1    Milk    Dairy   3.49        80
2   Bread   Bakery   2.99        60
3  Cheese    Dairy   5.99        45
4    Eggs    Dairy   4.49        90

In [84]:
df.sort_values("price")

  product category  price  quantity  total_value
0   Apple  Produce   1.99       150       298.50
2   Bread   Bakery   2.99        60       179.40
1    Milk    Dairy   3.49        80       279.20
4    Eggs    Dairy   4.49        90       404.10
3  Cheese    Dairy   5.99        45       269.55

In [85]:
df.sort_values("total_value", ascending=False)

  product category  price  quantity  total_value
4    Eggs    Dairy   4.49        90       404.10
0   Apple  Produce   1.99       150       298.50
1    Milk    Dairy   3.49        80       279.20
3  Cheese    Dairy   5.99        45       269.55
2   Bread   Bakery   2.99        60       179.40

In [86]:
import numpy as np

# Create a messy dataset with missing values
messy_data = [
    {"name": "Apple",  "category": "Produce", "price": 1.99,  "quantity": 150},
    {"name": "Milk",   "category": "Dairy",   "price": None,  "quantity": 80},
    {"name": "Bread",  "category": None,       "price": 2.99,  "quantity": 60},
    {"name": "Cheese", "category": "Dairy",   "price": 5.99,  "quantity": None},
    {"name": "Eggs",   "category": "Dairy",   "price": 4.49,  "quantity": 90}
]

messy_df = pd.DataFrame(messy_data)
messy_df

     name category  price  quantity
0   Apple  Produce   1.99     150.0
1    Milk    Dairy    NaN      80.0
2   Bread      NaN   2.99      60.0
3  Cheese    Dairy   5.99       NaN
4    Eggs    Dairy   4.49      90.0

In [87]:
messy_df.isnull()

    name  category  price  quantity
0  False     False  False     False
1  False     False   True     False
2  False      True  False     False
3  False     False  False      True
4  False     False  False     False

In [88]:
messy_df.isnull().sum()

name        0
category    1
price       1
quantity    1
dtype: int64

In [89]:
# Option 1 — Drop rows with any missing values
cleaned_df = messy_df.dropna()
cleaned_df

    name category  price  quantity
0  Apple  Produce   1.99     150.0
4   Eggs    Dairy   4.49      90.0

In [90]:
# Option 2 — Fill missing values with something meaningful
filled_df = messy_df.copy()
filled_df["price"] = filled_df["price"].fillna(0)
filled_df["quantity"] = filled_df["quantity"].fillna(0)
filled_df["category"] = filled_df["category"].fillna("Unknown")
filled_df

     name category  price  quantity
0   Apple  Produce   1.99     150.0
1    Milk    Dairy   0.00      80.0
2   Bread  Unknown   2.99      60.0
3  Cheese    Dairy   5.99       0.0
4    Eggs    Dairy   4.49      90.0

In [92]:
df.groupby("category").agg(
    total_products=("product", "count"),
    avg_price=("price", "mean"),
    total_value=("total_value","sum")
)

          total_products  avg_price  total_value
category
Bakery                 1   2.990000       179.40
Dairy                  3   4.656667       952.85
Produce                1   1.990000       298.50

In [93]:
# First table - products and their category
products_df = pd.DataFrame([
    {"product_id": 1, "name": "Apple",  "category": "Produce"},
    {"product_id": 2, "name": "Milk",   "category": "Dairy"},
    {"product_id": 3, "name": "Bread",  "category": "Bakery"},
    {"product_id": 4, "name": "Cheese", "category": "Dairy"},
    {"product_id": 5, "name": "Eggs",   "category": "Dairy"}
])

# Second table - pricing information
pricing_df = pd.DataFrame([
    {"product_id": 1, "price": 1.99, "quantity": 150},
    {"product_id": 2, "price": 3.49, "quantity": 80},
    {"product_id": 3, "price": 2.99, "quantity": 60},
    {"product_id": 4, "price": 5.99, "quantity": 45},
    {"product_id": 6, "price": 2.49, "quantity": 100}
])

print("Products table:")
print(products_df)
print("\nPricing table:")
print(pricing_df)

Products table:
   product_id    name category
0           1   Apple  Produce
1           2    Milk    Dairy
2           3   Bread   Bakery
3           4  Cheese    Dairy
4           5    Eggs    Dairy

Pricing table:
   product_id  price  quantity
0           1   1.99       150
1           2   3.49        80
2           3   2.99        60
3           4   5.99        45
4           6   2.49       100

In [94]:
inner = pd.merge(products_df, pricing_df, on="product_id", how="inner")
print("Inner Join:")
print(inner)

Inner Join:
   product_id    name category  price  quantity
0           1   Apple  Produce   1.99       150
1           2    Milk    Dairy   3.49        80
2           3   Bread   Bakery   2.99        60
3           4  Cheese    Dairy   5.99        45

In [95]:
# Left join - keep all products, fill missing pricing with NaN
left = pd.merge(products_df, pricing_df, on="product_id", how="left")
print("Left join:")
print(left)

Left join:
   product_id    name category  price  quantity
0           1   Apple  Produce   1.99     150.0
1           2    Milk    Dairy   3.49      80.0
2           3   Bread   Bakery   2.99      60.0
3           4  Cheese    Dairy   5.99      45.0
4           5    Eggs    Dairy    NaN       NaN

In [96]:
# Left join - keep all products, fill missing pricing with NaN
left = pd.merge(products_df, pricing_df, on="product_id", how="left")
print("Left join:")
print(left)

Left join:
   product_id    name category  price  quantity
0           1   Apple  Produce   1.99     150.0
1           2    Milk    Dairy   3.49      80.0
2           3   Bread   Bakery   2.99      60.0
3           4  Cheese    Dairy   5.99      45.0
4           5    Eggs    Dairy    NaN       NaN

In [97]:
# Outer join - keep everything from both tables
outer = pd.merge(products_df, pricing_df, on="product_id", how="outer")
print("Outer join:")
print(outer)

Outer join:
   product_id    name category  price  quantity
0           1   Apple  Produce   1.99     150.0
1           2    Milk    Dairy   3.49      80.0
2           3   Bread   Bakery   2.99      60.0
3           4  Cheese    Dairy   5.99      45.0
4           5    Eggs    Dairy    NaN       NaN
5           6     NaN      NaN   2.49     100.0